spring.datasource.url=${APP_DB_URL}
spring.datasource.username=${APP_DB_USERNAME}
spring.datasource.password=${APP_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

app.seed.local-data-enabled=${APP_SEED_LOCAL_DATA_ENABLED:false}
app.seed.city-external-id=${APP_SEED_CITY_EXTERNAL_ID:}
app.firebase.enabled=true
app.api.cors.allowed-origins=${app.frontend.url}
app.notifications.delivery.worker-enabled=false
app.notifications.devices.cleanup-enabled=false
