spring.datasource.url=${APP_DB_URL}
spring.datasource.username=${APP_DB_USERNAME}
spring.datasource.password=${APP_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

app.seed.local-data-enabled=true
