spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.jwt.access-expiration=1800000
app.jwt.refresh-short-expiration=86400000
app.jwt.refresh-long-expiration=2592000000
app.jwt.secret=${APP_JWT_SECRET}

app.auth.activation-token-expiration=345600000


app.encryption.password=${APP_ENCRYPTION_PASSWORD}
app.encryption.salt=${APP_ENCRYPTION_SALT}

app.mail.activation-base-url=http://localhost:8080/api/v1/auth/activate/
app.mail.from-address=no-reply@eventorganizer.local

app.seed.local-data-enabled=false

app.firebase.enabled=false
app.firebase.service-account-location=
