spring.datasource.url=${APP_DB_URL}
spring.datasource.username=${APP_DB_USERNAME}
spring.datasource.password=${APP_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

spring.mail.host=${APP_MAIL_HOST}
spring.mail.port=${APP_MAIL_PORT:587}
spring.mail.username=${APP_MAIL_USERNAME}
spring.mail.password=${APP_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.activation-base-url=${APP_MAIL_ACTIVATION_BASE_URL}
app.mail.from-address=${APP_MAIL_FROM_ADDRESS}

app.firebase.enabled=${APP_FIREBASE_ENABLED:false}
app.firebase.service-account-location=${APP_FIREBASE_SERVICE_ACCOUNT_LOCATION:}
